Fix invalid json of benchmark output
line/decaton pull request #228
Opened 2024-03-07 11:36 UTC by ocadaruma

- Now performance dashboard doesn't work because latest run produces invalid JSON output
    * https://line.github.io/decaton/commit-data/a3f14197b71c65a7aa8d83b78d5c9756dbf9ca89/tasks_100k_latency_10ms_concurrency_20-benchmark.json
- This is because current version of async-profiler output `Profiling started` on stdout and there seems to be no way to disable this
- To address this, I added `--file` option to the benchmark module to prevent async-profiler output and benchmark output are mixed

2024-03-07 11:53 UTC, ocadaruma commented
The invalid json broke performance dashboard so we will need to manually fix it and commit to `gh-pages` branch

2024-03-08 01:11 UTC, kawamuray requested changes

2024-03-08 01:11 UTC, kawamuray commented on benchmark/src/main/java/com/linecorp/decaton/benchmark/Main.java
> +    @Option(names = "--file", description = "Result file to write output to. If not specified, output to stdout")
ogh.. thanks again for another follow-up. Just a nit, would it be bertter to name this param `--output` following the convention of most command-line utilities?

2024-03-08 01:55 UTC, kawamuray approved these changes

2024-03-08 01:55 UTC, merged